### ISSUE TITLE
How it work?

### ISSUE THREAD

**Issue by KingDeadKnight** [ImagicalCorp/DynMapPE#1]
I found it few minuts ago and I searched how it works..
But I don't find the answers, so can you explain it to me?

Edit: Ohw, I've just seen that's it's not finish yet, I apologize.

**Comment by thebigsmileXD** [comment]
But this is my current project. Thanks for checking it out anyways.
@PEMapModder just found a way to save the top most blocks. Have to create a way to display them in web still
